version: '3.8'

services:
  backend:
    build: .
    container_name: academia-hub-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/academiahub  # Fixed database name
      SPRING_DATASOURCE_USERNAME: root  # Matches MYSQL_USER
      SPRING_DATASOURCE_PASSWORD: 12345  # Matches MYSQL_PASSWORD
    networks:
      - academia_network
    restart: always  # Optional

  mysql:
    image: mysql:8
    container_name: academia-hub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: academiahub  # Matches SPRING_DATASOURCE_URL
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mydbpassword
    ports:
       - "3306:3306"
    healthcheck:
      # test: ["CMD", "mysqladmin", "-uroot", "-p12345", "ping", "-h", "localhost"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      # interval: 10s
      # retries: 5
    networks:
      - academia_network

networks:
  academia_network:
    driver: bridge
