apiVersion: apps/v1
kind: Deployment
metadata:
  name: academia-hub-frontend
  namespace: academia-hub
spec:
  restartPolicy: Always
  replicas: 2
  selector:
    matchLabels:
      app: academia-hub-frontend
  template:
    metadata:
      labels:
        app: academia-hub-frontend
    spec:
      containers:
        - name: academia-hub-frontend
          image: 405894863687.dkr.ecr.ap-south-1.amazonaws.com/academia-hub-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: academia-hub-frontend-service
  namespace: academia-hub
spec:
  selector:
    app: academia-hub-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes the frontend to the internet
 
